name: Build Windows
on:
  workflow_dispatch:
env:
  BUILD_TYPE: Release
jobs:
  windows-latest:
    name: Windows Latest
    runs-on: windows-latest
    steps:
      - name: Checkout TechminoBackend source code
        uses: actions/checkout@v2

      - name: Setup vcpkg
        id: setup_vcpkg
        uses: lukka/run-vcpkg@v6
        with:
          setupOnly: true
          vcpkgDirectory: '${{github.workspace}}/vcpkg'

      - run: |
          $VCPKG_ROOT/vcpkg install drogon:x64-windows --clean-after-build
          shell: bash
        name: Run vcpkg in a inline script in this workflow.

      - name: Prints output of run-vcpkg's action
        run: echo "root='${{ steps.setup_vcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.setup_vcpkg.outputs.RUNVCPKG_VCPKG_TRIPLET_OUT }}'"

      - name: Cmake TechminoBackend
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          useVcpkgToolchainFile: true
          cmakeAppendedArgs: '-DCMAKE_BUILD_TYPE=$BUILD_TYPE'
          buildWithCMake: true
          buildDirectory: '${{github.workspace}}/build'
          buildWithCMakeArgs: '--config $BUILD_TYPE'