name: Build Windows
on:
  workflow_dispatch:
env:
  BUILD_TYPE: Release
jobs:
  windows-latest:
    name: Windows Latest
    runs-on: windows-latest
    steps:
      - name: Checkout TechminoBackend source code
        uses: actions/checkout@v2

      - name: Setup Vcpkg
        id: setup_vcpkg
        uses: lukka/run-vcpkg@v6
        with:
          setupOnly: true
          vcpkgGitCommitId: '981e65ce0ac1f6c86e5a5ded7824db8780173c76'
          vcpkgDirectory: '${{github.workspace}}/vcpkg'

      - name: Install Packages
        id: install_vcpkg
        uses: lukka/run-vcpkg@v6
        with:
          vcpkgGitCommitId: '981e65ce0ac1f6c86e5a5ded7824db8780173c76'
          vcpkgDirectory: '${{github.workspace}}/vcpkg'
          vcpkgTriplet: 'x64-windows'
          vcpkgArguments: 'drogon'

#      - name: Cmake TechminoBackend
#        uses: lukka/run-cmake@v3
#        with:
#          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
#          useVcpkgToolchainFile: true
#          cmakeAppendedArgs: '-DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}'
#          buildWithCMake: true
#          buildDirectory: '${{github.workspace}}/build'
#          buildWithCMakeArgs: '--config ${{env.BUILD_TYPE}}'