name: Build Windows
on:
  workflow_dispatch:
env:
  BUILD_TYPE: Release
jobs:
  windows-latest:
    name: Windows Latest
    runs-on: windows-latest
    steps:
      - name: Checkout TechminoBackend source code
        uses: actions/checkout@v2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v6
        with:
          setupOnly: true
          vcpkgDirectory: '${{github.workspace}}/vcpkg'

      - name: Cache vcpkg
        uses: lukka/run-vcpkg@v6
        with:
          vcpkgDirectory: '${{github.workspace}}/vcpkg'
          vcpkgTriplet: 'x64-windows'
          vcpkgArguments: 'drogon'

      - name: Cmake TechminoBackend
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          useVcpkgToolchainFile: true
          cmakeAppendedArgs: '-DCMAKE_BUILD_TYPE=$BUILD_TYPE'
          buildWithCMake: true
          buildDirectory: '${{github.workspace}}/build'
          buildWithCMakeArgs: '--config $BUILD_TYPE'