name: Build release
on: workflow_dispatch
env:
  BUILD_TYPE: Release
jobs:
  build_release:
    name: Ubuntu 18.04
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libjsoncpp-dev uuid-dev openssl libssl-dev zlib1g-dev postgresql-all libsqlite3-dev
          sudo apt install libbrotli-dev

      - name: Checkout Backend source code
        uses: actions/checkout@v2

      - name: Download Drogon release
        uses: actions/download-artifact@v2
        with:
          name: drogon-release
          path: ${{github.workspace}}/drogon-release

      - name: Install Drogon
        working-directory: ${{github.workspace}}/drogon-release
        shell: bash
        run: sudo make install

      - name: Cmake TechminoBackend
        shell: bash
        working-directory: ${{github.workspace}}
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build TechminoBackend
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Pack Release
        uses: actions/upload-artifact@v2
        with:
          path: ${{github.workspace}}/build
          name: