name: Build Drogon
on: workflow_dispatch
env:
  BUILD_TYPE: Release
jobs:
  build_release:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Drogon source code
        uses: actions/checkout@v2
        with:
          repository: an-tao/drogon
          submodules: true
          fetch-depth: 0
          path: drogon-src

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libjsoncpp-dev uuid-dev openssl libssl-dev zlib1g-dev postgresql-all libsqlite3-dev
          sudo apt install libbrotli-dev

      - name: Checkout Drogon source code
        uses: actions/checkout@v2
        with:
          repository: an-tao/drogon
          submodules: true
          fetch-depth: 0
          path: drogon-src

      - name: Cmake Drogon
        shell: bash
        working-directory: ${{github.workspace}}/drogon-src
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build Drogon
        working-directory: ${{github.workspace}}/drogon-src
        shell: bash
        run: |
          cd build
          sudo make

      - name: Cache Drogon
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/drogon-src/build
          key: ${{ runner.os }}-drogon-cache
