name: Build Windows
on:
  workflow_dispatch:
env:
  BUILD_TYPE: Release
jobs:
  windows-latest:
    name: Windows Latest
    runs-on: windows-latest
    steps:
      - name: Checkout TechminoBackend source code
        uses: actions/checkout@v2

      - name: Cache Vcpkg
        id: cache_vcpkg
        uses: actions/cache@v2
        with:
          path: C:/Users/runneradmin/AppData/Local/vcpkg/installed
          key: ${{ runner.os }}-vcpkg-cache

      - name: Install Dependencies
        if: steps.cache_vcpkg.outputs.cache-hit != 'true'
        run: vcpkg install drogon:x64-windows

      - name: Cmake TechminoBackend
        shell: cmd
        working-directory: ${{github.workspace}}
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/Users/runneradmin/AppData/Local/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build TechminoBackend
        working-directory: ${{github.workspace}}/build
        shell: cmd
        run: cmake --build . --config $BUILD_TYPE