name: Check dependencies
on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "greet"
  check_dependencies:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: apt helper action
        uses: ryankurte/action-apt@v0.2.0
        with:
          packages: "libjsoncpp-dev uuid-dev openssl libssl-dev zlib1g-dev postgresql-all"
